name: Sync Fork with Upstream and Create PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sync branch (create if not exists)
        uses: actions/checkout@v3
        with:
          ref: sync
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/MicrosoftDocs/WSL.git
          git fetch upstream
          git checkout -b sync-upstream-branch
          git merge upstream/main --no-commit

      - name: Set Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git commit -m "Sync with upstream changes" || echo "No changes to commit"
      - name: Push changes to sync branch
        run: |
          git push origin sync

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync with upstream changes
          branch: sync
          base: main
          title: "Sync with upstream"
          body: "This PR keeps the fork in sync with the upstream repository."
